- name: Install and start Prometheus
  hosts: localhost
  become: yes
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Ensure Prometheus is running
      service:
        name: prometheus
        state: started
        enabled: yes
